defaults: &defaults
  docker:
      - image: bepsays/ci-goreleaser:1.14.3
  environment:
    CGO_ENABLED: "0"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout:
          path: hugo
      - run:
            command: |
                git clone git@github.com:gohugoio/hugoDocs.git
                cd hugo
                go mod download
 
